require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - Rakefile
    - bin/**/*
    - config.ru
    - config/application.rb
    - config/boot.rb
    - config/environment.rb
    - config/environments/development.rb
    - config/environments/production.rb
    - config/environments/test.rb
    - config/initializers/assets.rb
    - config/initializers/content_security_policy.rb
    - config/initializers/filter_parameter_logging.rb
    - config/initializers/inflections.rb
    - config/initializers/permissions_policy.rb
    - config/puma.rb
    - db/schema.rb
    - node_modules/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - vendor/**/*

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
