name: CI

on:
  - pull_request
  - push

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run RuboCop
        run: bundle exec rubocop --parallel

      - name: Run HAML-Lint
        run: bundle exec haml-lint --parallel app/views
        if: always()

      - name: Run ESLint
        run: yarn run eslint app/javascript
        if: always()

      - name: Run Prettier
        run: yarn run prettier --check app/assets/stylesheets app/javascript
        if: always()
